[package]
name = "opentelemetry-langfuse"
version = "0.1.0"
edition = "2021"
authors = ["Tim Van Wassenhove <github@timvw.be>"]
license = "MIT OR Apache-2.0"
description = "OpenTelemetry integration for Langfuse observability"
repository = "https://github.com/genai-rs/opentelemetry-langfuse"
homepage = "https://github.com/genai-rs/opentelemetry-langfuse"
documentation = "https://docs.rs/opentelemetry-langfuse"
readme = "README.md"
keywords = ["opentelemetry", "langfuse", "observability", "tracing", "monitoring"]
categories = ["api-bindings", "web-programming::http-client", "development-tools::debugging"]
rust-version = "1.82"

[lints.rust]
unsafe_code = "forbid"

[lints.rustdoc]
broken_intra_doc_links = "warn"
private_intra_doc_links = "warn"
missing_crate_level_docs = "warn"
invalid_codeblock_attributes = "warn"
invalid_html_tags = "warn"
invalid_rust_codeblocks = "warn"
bare_urls = "warn"
unescaped_backticks = "warn"

[dependencies]

[dev-dependencies]

[features]
default = []
