# Configuration for release-plz
# https://release-plz.ieni.dev/docs/config

[workspace]
# Enable changelog generation
changelog_update = true

# Enable git releases and tags
git_release_enable = true
git_tag_enable = true

# Git release body template - ensures GitHub releases have proper content
git_release_body = """
## What's Changed

{%- if changelog %}
{{ changelog }}
{%- else %}
_No changelog available_
{%- endif %}

**Full Changelog**: https://github.com/genai-rs/opentelemetry-langfuse/compare/{{ previous_version }}...{{ version }}
"""

# PR settings
pr_labels = ["release"]
pr_draft = false
pr_name = "chore: release version {{version}}"

# PR body template - ensures PR descriptions show the changelog
pr_body = """
{%- for release in releases -%}
## 📦 {{ release.package }} {{ release.previous_version }} → {{ release.next_version }}

### 🔗 Compare Changes
[**View all changes since v{{ release.previous_version }}**](https://github.com/genai-rs/opentelemetry-langfuse/compare/v{{ release.previous_version }}...HEAD)

{%- if release.changelog %}

### 📋 Changelog

{{ release.changelog }}
{%- else %}

_No changelog available for this release_
{%- endif %}

{%- endfor %}

---
_This PR was generated by [release-plz](https://github.com/MarcoIeni/release-plz/)_
"""

# Publishing
publish = true
publish_allow_dirty = false