# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

# Use stable formatting options only
edition = "2021"
max_width = 100
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true

# The following options would be nice but are unstable:
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_strings = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true